baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Rishi Verma"
theme = "PaperMod"

[params]
  description = "Rishi Verma's Personal Website"
  author = "Rishi Verma"
  defaultTheme = "light"
  disableThemeToggle = true
  
  [params.profileMode]
    enabled = true
    title = "Rishi Verma"
    subtitle = "I'm a Master's student at Stanford working at the intersection of systems and AI."
    imageUrl = "/images/headshot.jpeg"
    imageWidth = 240
    imageHeight = 240
    
  # Social icons
  [[params.socialIcons]]
  name = "email"
  url = "mailto:verma.rishiraj@gmail.com"
  
  [[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/rishirv"
  
  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/rishirv"

# Main menu
[menu]
  [[menu.main]]
    name = "About"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Experience"
    url = "/experience/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 4