baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Rishi Verma"
theme = "PaperMod"

[params]
  description = "Rishi Verma's Personal Website"
  author = "Rishi Verma"
  defaultTheme = "light"
  
  [params.profileMode]
    enabled = true
    title = "Computer Systems & Artificial Intelligence"
    subtitle = "I'm a Stanford student working at the intersection of computer systems and AI."
    imageUrl = "/images/profile.jpg" # TODO: Add image
    imageWidth = 120
    imageHeight = 120
    
  # Social icons
  [[params.socialIcons]]
  name = "email"
  url = "mailto:verma.rishiraj@gmail.com"
  
  [[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/rishirv"
  
  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/rishirv"

# Main menu
[menu]
  [[menu.main]]
    name = "About"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Experience"
    url = "/experience/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 4